### PR TITLE
Add Dilithium as auth method in TLS 1.3

### PR DESCRIPTION
**Pull request by dimisik**
This PR adds the dilithium (2,3, and 4) as auth method in TLS 1.3.

Not ready to merge: 
Currently, the branch compiles, generates self-signed root CA certificates for dilithium, and generates the server key pair and certificate request to CA.

But, gives this error when the CA attempts to generate the signed server certificate:
> Signature verification error
140361263314752:error:0D0C50C7:asn1 encoding routines:ASN1_item_verify:unknown signature algorithm:crypto/asn1/a_verify.c:115:

Also, I was not able to automatically generate the object files with the command `make generate_crypto_objects`  and filled the related filled manually (it might be related).

### CODE REVIEW

**Comment by christianpaquin** [comment]
@dimisik, any idea why `make generate_crypto_objects` didn't work? Did you get an error?

**Comment by dimisik** [comment]
Yes, an undefined identifier error:

> crypto/objects/objects.txt:1696:Undefined identifier 1.3.6.1.4.1.772.1.2.2.2

**Comment by christianpaquin** [comment]
Can't put dots in the alg OID in the `object.txt` file; I've pushed an update. I'll test cert issuance next.

**Comment by christianpaquin** [comment]
@dimisik, I added the dilithium algs in `obj_xref.txt` and regenerated the crypto objects. This step was missing from the documentation, which I've also updated. I'm now facing a new error (wrong signature type) when I try to use a dilithium cert. Curious, is it working for you?

**Comment by dimisik** [comment]
@christianpaquin I just tried it.

EDIT: Yes, I am seeing the same thing on the client:

> 140119414884160:error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type:ssl/t1_lib.c:1251:

**Comment by csosto-pk** [comment]
This looks similar to what is described in https://github.com/openssl/openssl/issues/7126

Based on the packet captures, we see that the Dillithium algorithms are in the sig_algorithms extension in the Client Hello, but the client rejects the signature in the server response. I can't see the server cert_verify message because it is encrypted in TLS 1.3, but it looks like the server signs with an algorithm that is not in the original list sent by the client.

**Comment by csosto-pk** [comment]
It looks like the error is triggered in ssl/t1_lib.c in 
```
    if (lu == NULL
        || (SSL_IS_TLS13(s) && (lu->hash == NID_sha1 || lu->hash == NID_sha224))
        || (pkeyid != lu->sig
        && (lu->sig != EVP_PKEY_RSA_PSS || pkeyid != EVP_PKEY_RSA))) {
        SSLfatal(s, SSL_AD_ILLEGAL_PARAMETER, SSL_F_TLS12_CHECK_PEER_SIGALG,
                 SSL_R_WRONG_SIGNATURE_TYPE);
        return 0;
    }
```

More specifically it is triggered because 
``` pkeyid != lu->sig ```

The certificate from the server has the same OID (1.3.6.1.4.1.772.1.2.2.2) for the signature and the public key, so this should be  OK. 

I am not sure what public key and signature algorithm the client reads yet, but I think there is something wrong there.

**Comment by panburana** [comment]
*edit* It looks like when this error is happening pkeyid is set to 1207 (dilithium2) and lu->sig is 1198 (p256_picnicL1FS).
Server appears to be correctly sending dilithium2 but the client seems to be wanting to use P256_picnic.

**Comment by christianpaquin** [comment]
Ok, needs some digging down. I'll be out-of-office this and next week, I'll look into it when I'm back.

**Comment by dimisik** [comment]
We found the issue with @csosto-pk 
The entries in the ssl/ssl_cert_table.h file should follow the NID order.
It should work now

**Comment by csosto-pk** [comment]
Just for reference, the issue 
> 140119414884160:error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type:ssl/t1_lib.c:1251:

was triggered because 
```
    {EVP_PKEY_DILITHIUM2, SSL_aDILITHIUM2}, /* SSL_PKEY_DILITHIUM2 */    
    {EVP_PKEY_DILITHIUM3, SSL_aDILITHIUM3}, /* SSL_PKEY_DILITHIUM3 */ 
    {EVP_PKEY_DILITHIUM4, SSL_aDILITHIUM4}, /* SSL_PKEY_DILITHIUM4 */
```

were in the wrong order in ssl/ssl_cert_table.h. Their order should match the indices defined 
```
# define SSL_PKEY_DILITHIUM2     19
# define SSL_PKEY_DILITHIUM3     20
# define SSL_PKEY_DILITHIUM4     21
```

in ssl/ssl_locl.h. 

Thanks to @dimisik for his work.

**Review by dstebila — APPROVED** [review]

**Comment by christianpaquin** [comment]
@dimisik, @csosto-pk, I'm glad you were able to figure this out. Any intention of adding the hybrid suites for dilithium?

**Comment by dimisik** [comment]
@christianpaquin we will continue initially with pure PQ schemes such as Falcon. I will keep you all posted for updates.

**Pull request merged**
