### PR TITLE
Integrate Falcon in TLS 1.3

### PR DESCRIPTION
**Pull request by dimisik**
This PR adds Falcon in TLS 1.3, provided  open-quantum-safe/liboqs#533 is merged.
I will update it accordingly then if necessary.

### CODE REVIEW

**Comment by xvzcf** [comment]
Closing this as it is superseded by https://github.com/open-quantum-safe/openssl/pull/107.

**Comment by csosto-pk** [comment]
I don't see Falcon in #107 . 
Should we assume someone needs to add them from scratch by using the new template?

**Comment by xvzcf** [comment]
Yes: once the PR is merged in, "from scratch" will mean just adding some algorithm information to [this file](https://github.com/open-quantum-safe/openssl/pull/107/files#diff-bdb23fcf69159621f2f0f126e4dc1eec) as opposed to modifying 20 files.

**Comment by csosto-pk** [comment]
@xvzcf are we supposed to use the template now and create a new PR to add Falcon or picnic2 (PR #102) or any other algorithm?

**Comment by xvzcf** [comment]
Yes, I've added instructions for how to do so [here](https://github.com/open-quantum-safe/openssl/wiki/Contributing-Guide). If anything's missing/unclear, let me know.

**Pull request closed without merging**
