### PR TITLE
Add Dockerized Environment for Improved Installation and Usage Experience

### PR DESCRIPTION
**Pull request by salmanhiro**
This PR addresses the challenges faced by users during the installation process by introducing a Dockerized environment for the project. The aim is to provide a consistent and reliable setup that mitigates issues arising from differences in user environments.The installation process of the project in local can encounter various difficulties due to differences in operating systems, dependencies, and configurations across users' environments. These discrepancies could lead to be challenging for users to get the project up and running smoothly.

The PR includes the following changes:

* Added a Dockerfile that builds the project's environment based on the Python 3.9 Alpine image. It installs the required dependencies. The Dockerfile also sets the working directory and clones the necessary repositories (openssl and liboqs), compiling and installing them.

* Created a docker-compose.yml file that defines the services and volumes for the Docker container. The shared volume is configured to link the host and the container, ensuring that generated files are accessible outside the container.

* Instruction for OpenSSL commands on the Docker container.

These changes provide users with an easy and reproducible way to set up and run the project in a Docker environment. The Dockerized environment ensures consistent execution and simplifies the installation process.

##### Checklist

- [x ] documentation is added or updated

### CODE REVIEW

**Comment by baentsch** [comment]
Thanks for this contribution. I'm afraid it comes a bit too late: We had such image in docker hub in the image [openquantumsafe/curl](https://hub.docker.com/repository/docker/openquantumsafe/curl/general) (generated from https://github.com/open-quantum-safe/oqs-demos/tree/main/curl) but replaced this by now with the more future-proof OpenSSL3 version (given the [EOL notice for (oqs)openssl111](https://github.com/open-quantum-safe/openssl/releases)). If you'd like to try it, it still is accessible under the ":0.7.2" tag.

Going forward, would you possibly consider checking out https://hub.docker.com/repository/docker/openquantumsafe/oqs-ossl3/general (and the generating code at https://github.com/open-quantum-safe/oqs-demos/tree/main/openssl3) to state improvements missing there (and maybe add them via PR there)?

**Comment by salmanhiro** [comment]
> Thanks for this contribution. I'm afraid it comes a bit too late: We had such image in docker hub in the image [openquantumsafe/curl](https://hub.docker.com/repository/docker/openquantumsafe/curl/general) (generated from https://github.com/open-quantum-safe/oqs-demos/tree/main/curl) but replaced this by now with the more future-proof OpenSSL3 version (given the [EOL notice for (oqs)openssl111](https://github.com/open-quantum-safe/openssl/releases)). If you'd like to try it, it still is accessible under the ":0.7.2" tag.
> 
> Going forward, would you possibly consider checking out https://hub.docker.com/repository/docker/openquantumsafe/oqs-ossl3/general (and the generating code at https://github.com/open-quantum-safe/oqs-demos/tree/main/openssl3) to state improvements missing there (and maybe add them via PR there)?

Thanks! I think I will take a look into docker hub image, try it, and apply some improvements

**Comment by baentsch** [comment]
> Thanks! I think I will take a look into docker hub image, try it, and apply some improvements

Thanks very much! May I invite you to also take a look at the [Dockerfile in the branch "mb-opensslupdate"](https://github.com/open-quantum-safe/oqs-demos/blob/mb-opensslupdate/openssl3/Dockerfile) to see the state of some experiments for better caching in `docker buildx` usage....

**Comment by dstebila** [comment]
The OpenSSL project has indicated that OpenSSL 1.1.1 will reach end-of-life in September 2023.  As such, we are discontinuing development on OQS-OpenSSL 1.1.1, and recommend all users switch to OpenSSL 3 and the [OQS Provider for OpenSSL 3](https://github.com/open-quantum-safe/oqs-provider/), which provides all the same functionality that OQS-OpenSSL 1.1.1 does.  Hence we are closing open pull requests and issues in OQS-OpenSSL 1.1.1 as won't-fix.

**Pull request closed without merging**
