### PR TITLE
Added more OQS KEM and documented nist-branch.

### PR DESCRIPTION
**Pull request by christianpaquin**
*NOT READY FOR MERGE*: need to test all new schemes.

Added OQS default kem and the nist-supported kem. Also documented how to build OpenSSL with OQS's nist-branch.

### CODE REVIEW

**Comment by christianpaquin** [comment]
Code compiles with both nist-branch and master. I need to test the (many!) new schemes before being ready to merge.

**Comment by christianpaquin** [comment]
I can't test the nist-branch + OpenSSL 1.1.1 anymore: running the programs always fail saying that liboqs.so can't be found, even if I specified the "no-shared" configure option. It was failing on my dev box, and I also get the same thing on a clean VM. I don't think I introduced something in this PR that would affect that. Can someone else repro? @dstebila ? @smashra ?

**Comment by smashra** [comment]
I'm working on testing OpenSSL 1.1.1 through the integration script.

I'm working with everything as shared library.

I'm getting the same errors.
Looking into it.

**Comment by dstebila** [comment]
The problem is that running OpenSSL 1.1.1 `./Configure no-shared` tells OpenSSL's build system not to build shared versions of libcrypto and libssl, but still allows us to make use of shared libraries for components it depends on, including liboqs.  If liboqs.so is present in /path/to/openssl/oqs, then OpenSSL will build against the liboqs.so shared library, even if you were not building an OpenSSL shared library.

The README.md on OQS-OpenSSL\_1]\_1\_1-stable build instructions for liboqs master disable building liboqs.so with the option `--enable-shared=no`.  We currently don't have instructions for nist-branch (we need to add them).  There's no option to tell the basic Makefile in nist-branch to not build a shared library, so what you need to do is delete liboqs.so from /path/to/openssl/oqs/lib after you've done the nist-branch `make install PREFIX-/path/to/openssl/oqs`.

**Comment by smashra** [comment]
Why do we have to build no-shared version of OQS_OpenSSL at all ?

**Comment by dstebila** [comment]
You can build the shared version and it will work, you just have to make sure that libssl and libcrypto are in a place where the runtime linker will find them.  Since we recommend that people don't make install our OpenSSL into the system default /usr directory, they'd have to correctly specify the LD\_LIBRARY\_PATH.  I thought it would be simpler for the (basic) instructions to just avoid shared libraries.

**Comment by christianpaquin** [comment]
So, how can you build liboqs-nistbranch w/ OpenSSL? Is there a simple one-liner "make" I can invoke? I'd like to test the new ciphers sonner than later.

**Comment by smashra** [comment]
Christian, checkout the openssh run script under testing repository.

Liboqs nist is being built with openssl.

**Comment by smashra** [comment]
I’ll try building it and let you know.

Why i mentioned the script was to get ideas about compiler flags.

**Comment by dstebila** [comment]
@christianpaquin 

~~~bash
cd liboqs-nist
make -j
make install PREFIX=/path/to/openssl/oqs
cd ../openssl
rm oqs/lib/liboqs.so
./Configure no-shared linux-x86_64-cc
make -j
~~~

**Comment by christianpaquin** [comment]
Got it, thanks, I'll try later this evening.

**Comment by smashra** [comment]
These are the steps I took to build everything shared:
=========================================

mkdir tmp
cd tmp
git clone -b  OpenSSL_1_0_2-stable https://github.com/openssl/openssl.git
openssl-std
cd openssl-std
env CFLAGS=-fPIC ./Configure shared darwin64-x86_64-cc
--prefix=`pwd`/../install
make -j
make depend
make install

cd ..
git clone -b  OQS-OpenSSL_1_1_1-stable
https://github.com/openssl/openssl.git
git clone --branch nist-branch
https://github.com/open-quantum-safe/liboqs.git
cd liboqs
make -j OPENSSL_INCLUDE_DIR=`pwd`/../install/include
OPENSSL_LIB_DIR=`pwd`/../install/lib
make install PREFIX=`pwd`/../openssl/oqs


cd ..
cd openssl
./Configure no-shared darwin64-x86_64-cc
make -j
make depend

**Comment by smashra** [comment]
Correction:

The last block is shared and not no-shared

cd ..
cd openssl
./Configure shared darwin64-x86_64-cc
make -j
make depend

**Comment by christianpaquin** [comment]
Ok, thanks @dstebila, deleting oqs/lib/liboqs.so allowed me to build and link properly. I'm now testing the PR; I get some seg faults. Investigating...

**Comment by christianpaquin** [comment]
I've pushed a fix for the seg faults I experienced: I missed a function in which to add the nist-branch algs. I was able to test the new algs. Most of them succeed, but the ones with big keys fail: bigquake, titanium, ledakem (C5, no 3 & 4), and lima (sp 2062). I'll disable them for v0.1.0; we can investigate a workaround in the next version (increase some buffers, perhaps). I hope to complete this tonight.

**Comment by christianpaquin** [comment]
Disabled failing schemes; works for me.

**Comment by christianpaquin** [comment]
Our fork runs the unmodified OpenSSL travis build, which doesn't know how to build OQS. We'll need to modify it, or turn off travis for 0.1.0.

**Review by dstebila — APPROVED** [review]

**Comment by dstebila** [comment]
Merged.  I updated the instructions and tested on my Mac and Ubuntu 14.  I also added a `make install-noshared` target in liboqs-nist so that it would not install liboqs.so.

**Comment by christianpaquin** [comment]
Awesome, thanks

**Pull request merged**
