### PR TITLE
Use OpenSSL error schemes

### PR DESCRIPTION
**Pull request by thomwiggers**
The OpenSSL error handling works as follows:

* Per module (e.g. `crypto/ec`) a namespace is made (`ECerr`)
* In that namespace, all `ECerr` calls are scraped
* The location parameter should be `EC_F_<functionname>`
* The reason should be `ERR_R_reason`.
* Then you run `make errors`: this scrapes the above out of the places
where they are used and puts them into the appropriate headerfiles.

I've turned `OQSerr` back into `ECerr`, because otherwise `make errors`
was broken. I've also added some reasons other than `ERR_R_FATAL`.

### CODE REVIEW

**Comment by dstebila** [comment]
So I understand, there's no particular reason to choose the `EC` prefix, just that we want to piggy-back on an existing prefix rather than introduce our own.  And introducing our own is tricky because the way `make errors` works is that it uses `util/mkerr.pl` to search through the source files looking for error codes, but because our error codes aren't actually present in a sub-directory of `crypto/`, ours wouldn't be found?

**Comment by thomwiggers** [comment]
Yeah, I wasn't able to figure out how to get that to work. There's some file where you need to add these namespaces, but it seemed to be quite tied to the subdirectories. I'm also not sure if you're allowed to use e.g. `DHerr` in the `crypto/ec` folder...

**Review by dstebila — CHANGES_REQUESTED** [review]
This failed to compile for me because a bunch of the error reasons were prefixed with `ERR_R_` but those aren't being detected by `make errors`.  I changed them to `EC_R_`.  But then I tried to push my changes to your commit, and for some reason it's being rejected.  Can you apply the changes in the attached [diff.txt](https://github.com/open-quantum-safe/openssl/files/2631631/diff.txt)?

**Comment by thomwiggers** [comment]
Merged and rebased. Sorry for taking so long, I'm in the midst of moving houses.

**Review by dstebila — APPROVED** [review]

**Comment by dstebila** [comment]
No worries, thanks for the updates.

**Pull request merged**
