### PR TITLE
Only use hybrid level 1 KEMs in default curves list

### LINKED ISSUE #162: Reduce number of default KEX algorithms
Having a large number of default KEX algorithms is causing problems in software that expects a shorter list.  We should reduce the list of default KEX algorithms in TLS 1.3 to just the level 1 hybrids.

### PR DESCRIPTION
**Pull request by dstebila**
Fixes #162

### CODE REVIEW

**Comment by christianpaquin** [comment]
Looks good. Maybe we could trim the list even more, by keeping only one per family (e.g., only sikep434, not 503). What do you think?

**Comment by baentsch** [comment]
Agree with @christianpaquin: 1 _conceptually_ different algorithm per family also was my thinking. So maybe keep (frodo)_shake and _aes variants, but certainly not more than 1 from `sidhp...` and `sikep...`. 

But I see a bigger issue now when looking at this code: With this, we really completely remove algorithms from `openssl` usage -- which isn't so great given what we currently have (the ability to run all candidates side by side, e.g., in performance as well as further downstream app tests, also against classic crypto of the same level). 

So what about this proposal (maybe now, maybe later): Create 3 different lists instead of only 1 (`eccurves_default`), say `ecccurves_level1` (& _2,_3) and make them "run-time activatable", e.g. by switching this OpenSSL code
```
        if (s->ext.supportedgroups == NULL) {
            *pgroups = eccurves_default;
            *pgroupslen = OSSL_NELEM(eccurves_default);
        } else {
```
suitably, e.g., to something like this
```
        if (s->ext.supportedgroups == NULL) {
            switch (atoi(getenv("NIST_STRENGTH_LEVEL"))) { // or some command line option?
            2: 
               *pgroups = eccurves_level2;
               *pgroupslen = OSSL_NELEM(eccurves_level2);
               break;
            3: 
               *pgroups = eccurves_level3;
               *pgroupslen = OSSL_NELEM(eccurves_level3);
               break;
            default:
               *pgroups = eccurves_level1;
               *pgroupslen = OSSL_NELEM(eccurves_level1);
            }
        } else {
```
I'd actually also suggest to put the classic algorithms onto the same "strength" list(s): e.g., "X25519" on _level1, "X448" on _level2 (or 3) to permit running the whole openssl -- and all downstream apps at a specific strength level -- classic as well as PQ crypto.

**Comment by dstebila** [comment]
> But I see a bigger issue now when looking at this code: With this, we really completely remove algorithms from `openssl` usage -- which isn't so great given what we currently have (the ability to run all candidates side by side, e.g., in performance as well as further downstream app tests, also against classic crypto of the same level).

No, we don't remove them fully from openssl usage.  They're just not the default algorithms.  You can run `openssl s_server -curves kyber1024 ...` and `openssl s_client -curves kyber1024 ...` and it will work fine.  You just have to explicitly enable these level 3 / 5 KEMs.  I thought this was the behaviour we were looking for.

**Comment by baentsch** [comment]
Ah, OK -- then I read the code incorrectly. Thanks for the clarification! I'll better run the stuff before I comment :-(

**Comment by dstebila** [comment]
Updated after sync with 1.1.1f #167. @christianpaquin can you review once CI tests pass?

**Comment by christianpaquin** [comment]
`make  tests` fail for me; @dstebila, do they pass for you? This is probably a result of the 111f merge rather than your minimal changes.

**Comment by dstebila** [comment]
`circleci local execute --job ubuntu-bionic-x86_64` passed for me.

**Comment by christianpaquin** [comment]
> `circleci local execute --job ubuntu-bionic-x86_64` passed for me.

And that runs "make test", correct? (I see it in the circleci's `config.yml`. If so, then that looks good.

**Review by christianpaquin — APPROVED** [review]

**Pull request merged**
