### PR TITLE
Replace function by #define for compile-time initialisation

### LINKED ISSUE #48: Building fails
I'm getting a whole bunch of errors like

```
ssl/t1_trce.c:563:6: error: initializer element is not constant
     {OQS_KEM_CURVEID(NID_OQS_ledakem_C1_N02), "ledakem_C1_N02"},
      ^~~~~~~~~~~~~~~
ssl/t1_trce.c:563:6: note: (near initialization for 'ssl_groups_tbl[58].num')
```

### PR DESCRIPTION
**Pull request by thomwiggers**
This should fix #48 (in combination with fixes from #49)

### CODE REVIEW

**Comment by dstebila** [comment]
Thanks Thom. We haven't been using gcc-8 so maybe that's why we didn't trigger it. @christianpaquin  are you able to take a look?

**Comment by christianpaquin** [comment]
These used to be macros, but were changed to functions to avoid intertwined macros when adding the nist-branch support. I'll take a look.

**Comment by christianpaquin** [comment]
I tried to update this PR but I didn't have permission. I created PR #51 with these (slightly modified) changes, and some others changes getting rid of similar functions (currently causing warnings). @thomwiggers, can you test PR #51?

**Comment by christianpaquin** [comment]
This PR shouldn't have been merged; it is superceded by PR #51.

**Comment by thomwiggers** [comment]
You based #51 on this commit; because #51 got merged, including 392d53a, this commit got automatically marked as merged.

**Comment by dstebila** [comment]
So everything's fine?

**Comment by christianpaquin** [comment]
Yes, I double-checked the final files; all good.

**Pull request merged**
