### PR TITLE
automate setting security/NIST levels in generate.py using liboqs input 

### LINKED ISSUE #315: Validate claimed NIST levels
https://github.com/open-quantum-safe/oqs-provider/issues/23 detected that one algorithm's claimed NIST level was incorrect. This was not detected earlier also because [the OpenSSL generate.yml](https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-template/generate.yml) can deviate from claimed NIST levels in `liboqs`. This issue to suggest a cross-validation of generate.yml with claimed `liboqs` NIST levels.

### PR DESCRIPTION
**Pull request by baentsch**
Fixes #315 

This new logic could also be used to completely do away with fields "[bits_]security" in `generate.yml` (as it can deduce them from `liboqs`' `claimed_nist_level`. What'd you think @dstebila @xvzcf ?

### CODE REVIEW

**Comment by xvzcf** [comment]
I'm not so sure about this: I think we should keep additional processing in `generate.py` to a minimum so as to ensure what the jinja fragments get is close or equal to what is in `generate.yml`, and compiling minimal C code in a python script also seems like a rather complex addition.

**Comment by baentsch** [comment]
Compiling code looked more simple to me than exposing the NIST levels to downstream code by other means. Whatever, then do you suggest not dealing with #315? Or do you suggest another approach?

**Comment by xvzcf** [comment]
> Compiling code looked more simple to me than exposing the NIST levels to downstream code by other means. Whatever, then do you suggest not dealing with #315? Or do you suggest another approach?

My first thought was that downstream projects could use the coming-soon&trade; YAML documentation sheets in liboqs, but I haven't thought it through. What do you think?

**Comment by baentsch** [comment]
> My first thought was that downstream projects could use the coming-soon™ YAML documentation sheets in liboqs, but I haven't thought it through. What do you think?

Good for me _if_ those YAML files are "the source of truth" (for `liboqs` code/constants, incl. test suite): If that were given, I'd be fine reading them in for doing NIST-level dependent "stuff" in downstream projects: Main thing is that `liboqs` internal NIST-level logic (or even code) shall not be different from what the downstreams "think"/know about them.

**Comment by baentsch** [comment]
> Good for me _if_ those YAML files are "the source of truth" (for liboqs code/constants, incl. test suite)

Thinking this through some more, I wonder whether it's really worthwhile changing what this PR already provides: Rationale: In order to obtain the same information from the YML files, we 

a) finally have to do them (and that's _a long time_ in the making, so if this is a harbinger for the future, they never will be eagerly maintained) then/therefore 
b) have to validate those files match the actual code, i.e., develop new test cases for this and finally, 
c) parse the YML files in downstream projects such as this.

Isn't it much easier and more reliable to simply query liboqs for the NIST levels that the actual code provides? Or put it another way: Does anyone volunteer to implement a)-c) to replace this PR? I'm not over-eager to be honest.....

**Comment by baentsch** [comment]
@dstebila Rebased the PR so you can investigate as per last week's meeting. Looking over the changes, I'm baffled that we apparently still have code points like "p256_kyber90s1024: 1263" (not present any more if this PR is merged).

**Comment by dstebila** [comment]
> @dstebila Rebased the PR so you can investigate as per last week's meeting. Looking over the changes, I'm baffled that we apparently still have code points like "p256_kyber90s1024: 1263" (not present any more if this PR is merged).

I'm not able to run what's here successfully.  When I run `python3 oqs-template/generate.py`, it results in code that has basically removed all hybrids (e.g., https://github.com/open-quantum-safe/openssl/blob/1ef99fbe2c7f0f15f755e0618c541d80c1b70fc7/oqs-interop-test/common.py#L19 is empty). So I'm not confused about how to proceed since it's not in the state I expected...

**Comment by baentsch** [comment]
> I'm not able to run what's here successfully. ... it results in code that has basically removed all hybrids

That's obviously not what should happen; checking the code again, the problem is caused by the platform-restriction added to let the test compilations go through; thus, the `bit_security` entries only get added on `linux`. So I presume you ran this on another platform? The latest commit changes the code to stop when this is the case. It _might_ run on OSX, but I don't have such platform to test locally. It surely will not run on Windows. So the questions are whether a) anyone could try on OSX (after suitably "darwin-enabling" the platform guard `if sys.platform=="linux":`) and b) whether we _need_ to have `generate.py` run on other platforms, too (possibly even adding it to CI)?

**Comment by dstebila** [comment]
@baentsch I think this should do it, at least in terms of reading the NIST levels from the liboqs algorithm datasheets.

**Comment by baentsch** [comment]
> reading the NIST levels from the liboqs algorithm datasheets.

Agreed, it does. However, this does not ascertain that the NIST levels in `liboqs` and `oqs-openssl` do match, as the former are not read from the datasheets. Hence, this code does not fix #315. It would, of course, if similar NIST level "doc->src ascertainment" would be added to `liboqs`: Is that your intention?

**Comment by dstebila** [comment]
> > reading the NIST levels from the liboqs algorithm datasheets.
> 
> Agreed, it does. However, this does not ascertain that the NIST levels in `liboqs` and `oqs-openssl` do match, as the former are not read from the datasheets. Hence, this code does not fix #315. It would, of course, if similar NIST level "doc->src ascertainment" would be added to `liboqs`: Is that your intention?

Do you mean that there's no check that the security levels in liboqs/docs/algorithms/\*/\*.yml and e.g. liboqs/src/kem/sike/kem_sike.c (and all other KEMs and SIGs) match?  If so, I agree that's something that should be checked, but should be done in liboqs.  

If you mean that there's something else here in OQS-OpenSSL where matching security levels are not checked, then I'm not sure what you're referring to.  I notice that in openssl/oqs-template/generate.yml there are (for KEMs) `extra_nids` hybrid groups that mix with e.g. x25519 that could be checked, and (for SIGs) the `mix_with` hybrid combinations that could be checked.

**Comment by baentsch** [comment]
>  If so, I agree that's something that should be checked, but should be done in liboqs.

Yes, that's what I mean. And agreed, it's something that needs to be done in `liboqs`. Unsure where, though... New script (checking doc/src "agreement")?

**Comment by dstebila** [comment]
> > If so, I agree that's something that should be checked, but should be done in liboqs.
> 
> Yes, that's what I mean. And agreed, it's something that needs to be done in `liboqs`. Unsure where, though... New script (checking doc/src "agreement")?

I've created https://github.com/open-quantum-safe/liboqs/pull/1070 to resolve that. 

So I think there's nothing left to do on this PR; if you're happy with it, please approve the review and we can merge.

**Comment by baentsch** [comment]
> if you're happy with it, please approve the review and we can merge.

For the record: Together with https://github.com/open-quantum-safe/liboqs/pull/1070 I'm happy with this approach. However, I'm afraid I cannot approve as I'm listed as original PR submitter (who arguably shouldn't be able to approve). So, @xvzcf @christianpaquin, could either of you please check and click "Approve"?

**Comment by dstebila** [comment]
> > if you're happy with it, please approve the review and we can merge.
> 
> For the record: Together with [open-quantum-safe/liboqs#1070](https://github.com/open-quantum-safe/liboqs/pull/1070) I'm happy with this approach. However, I'm afraid I cannot approve as I'm listed as original PR submitter (who arguably shouldn't be able to approve). So, @xvzcf @christianpaquin, could either of you please check and click "Approve"?

I can override as administrator. :)

**Pull request merged**
