### PR TITLE
Add msrcln16 & sidh to openssl

### PR DESCRIPTION
**Pull request by christianpaquin**
Added RLWE-MSRLN16 and SIDH-CLN16 to the OQS OpenSSL integration.

### CODE REVIEW

**Comment by dstebila** [comment]
Several of the hybrid ciphersuites don't seem to be working: the two newly added ones as well as OQSKEX-LWE-FRODO-RECOMMENDED-ECDHE.  I haven't been able to fix it.  

Reproduce by running a server with
~~~
apps/openssl s_server -cipher OQSKEX-LWE-FRODO-RECOMMENDED-ECDHE
~~~
and a client with
~~~
apps/openssl s_client -cipher OQSKEX-LWE-FRODO-RECOMMENDED-ECDHE
~~~
(or RLWE-MSRLN16-ECDHE or SIDH-CLN16-ECDHE).  

But RLWE-BCNS15-ECDHE and RLWE-NEWHOPE-ECDHE seem to work.  

So perhaps I screwed up something in the Frodo commit, and one should compare against the BCNS15 or NewHope commits to see what's different.

**Comment by christianpaquin** [comment]
I'll take a look

**Comment by christianpaquin** [comment]
Strangely enough, the hybrid ciphers work in my [Bash on Ubuntu on Windows](https://msdn.microsoft.com/commandline/wsl/about) (Linux) and pure Windows environment, but fails on my Ubuntu box. I'll have to debug on Linux directly.

**Comment by christianpaquin** [comment]
Found and fixed the issue. It seems that having un-ordered cipher IDs in tls1.h and s3_lib.c (RLWE-MSRL16 is 0xFF40 and appeared before LWE-FRODO which is 0xFF30) caused the problem. @dstebila, try again with this new commit.

**Pull request merged**
