### PR TITLE
Updated code to OQS's KEM API.

### PR DESCRIPTION
**Pull request by christianpaquin**
Updated code to use OQS's KEM API.

### CODE REVIEW

**Comment by christianpaquin** [comment]
There is a problem with the hybrid case. Investigating before merging...

**Comment by christianpaquin** [comment]
Ok, I fixed the typo in the OQS macros that prevented the hybrid case to work. This can go in now. @dstebila; you can take a look. I'll update the OpenSSL project once again after OQS's issue [380](https://github.com/open-quantum-safe/liboqs/issues/380) is completed.

**Comment by dstebila** [comment]
When I try to build this against the current master [493e5ec](https://github.com/open-quantum-safe/liboqs/commit/493e5ece376d7c70213271bbb54970aadd15b0e5), I get the following error:

```
crypto/ec/oqs_meth.c:277:29: error: no member named 'priv_key_len' in
      'struct OQS_SIG'
    int buflen = oqskey->s->priv_key_len + oqskey->s->pub_key_len, penclen;
```

Should I be building this against a version of master prior to when [#368](https://github.com/open-quantum-safe/liboqs/pull/368) landed, e.g. [a237410](https://github.com/open-quantum-safe/liboqs/commit/a23741082bbb2222f05708f6da37b87f0797b47e)?  If so, we should update the README's `git clone` instruction to point to that commit until we are synced with the head of master.

**Comment by christianpaquin** [comment]
I'll check; there might have been a confusion with the multiple versions of OQS in my dev environment.

**Comment by christianpaquin** [comment]
I pushed an update integrating changes to OQS's sig api. @dstebila, you can look again once we land OQS's [PR391](https://github.com/open-quantum-safe/liboqs/pull/391) (to make sure there aren't new changes)

**Comment by dstebila** [comment]
Works for me after OQS PR 391 landed.

**Pull request merged**
