### PR TITLE
Adds spring2020 OQS algs

### PR DESCRIPTION
**Pull request by christianpaquin**
Adds latest OQS algorithms. Addresses issue #194.

##### Checklist
- [X] Add KEMs
- [ ] Add sigs

### CODE REVIEW

**Comment by christianpaquin** [comment]
@dstebila, @xvzcf; I started by adding the only missing KEM: Classic McEliece. It's crashing. I remember NTS failing in our TLS paper; are we expecting Classic McEliece to work? I don't have too much time to investigate this failure; should we skip it?

**Comment by xvzcf** [comment]
I can spend some time next week looking at it.

**Comment by christianpaquin** [comment]
> I can spend some time next week looking at it.

Ok, I'll create another PR for the sigs.

**Comment by dstebila** [comment]
> @dstebila, @xvzcf; I started by adding the only missing KEM: Classic McEliece. It's crashing. I remember NTS failing in our TLS paper; are we expecting Classic McEliece to work? I don't have too much time to investigate this failure; should we skip it?

Ah, Classic McEliece will not work in TLS 1.3, since the maximum public key size allowed in key exchange messages in TLS 1.3 is 2^16-1 bytes, and Classic McEliece public keys are all bigger than that.  Same as with NTS.  So yes, we should skip Classic McEliece here.

**Comment by christianpaquin** [comment]
Closing PRs as no new KEMs need to be added.

**Comment by baentsch** [comment]
Reading the chain above makes me wonder whether it wouldn't be sensible to add things like this to the README (say in a 'supported algs' subsection) saying why certain things are _not_ supported (McEliece b/o size; Leda b/o vulnerability; others?), maybe with an issue to resolve it?

Advantage: Others also know about this (and in an ideal world maybe offer help resolving the issues).

**Comment by xvzcf** [comment]
Opened https://github.com/open-quantum-safe/openssl/issues/203 to track this.

**Pull request closed without merging**
