### PR TITLE
Merged upstream tag 1.1.1f 

### PR DESCRIPTION
**Pull request by christianpaquin**
Merges upstream tag `OpenSSL_1_1_1f`. Fixes issue #161, deprecates PR #164.

### CODE REVIEW

**Comment by christianpaquin** [comment]
@baentsch, @dstebila, @xvzcf; this new update fixes the issue we had with 1.1.1e, but it's now blocking due to an error with `undefined reference to GetX86Info` in OQS, which I think as been introduced with the CPU feature work (right?) Could one of you take a look? Does OpenSSL need to be updated? Are these platforms compatible with the function?

**Comment by xvzcf** [comment]
Looking at it.

**Comment by baentsch** [comment]
@xvzcf @gadoofou87 : I think I understand it: the failure is due to this `cmake` instruction not working with static libs (it works like a charm with shared libs): 
```
if(DEFINED CPUFEATURES_LIBRARY)
    target_link_libraries(oqs PRIVATE ${CPUFEATURES_LIBRARY})
endif()
```

The `cpu_features` symbol(s) are (well, should be) "localised" into liboqs and this way be available to downstream apps like openssl (again, for shared libs it works this way but not for static ones).
  
-> Does any one of you know why this is so? I checked `make VERBOSE=1` output and indeed, unlike during shared linking, no reference to `-lcpu_features` is made there. Is this a `cmake` bug?

**Comment by christianpaquin** [comment]
> Looking at it.

Any update @xvzcf ?

**Comment by xvzcf** [comment]
> > Looking at it.
> 
> Any update @xvzcf ?

It was not as straightforward as I thought, and I've been running into some issues. Working to get them fixed however. I'll post an update tomorrow.

**Comment by xvzcf** [comment]
Fixed.

**Review by dstebila — APPROVED** [review]

**Pull request merged**
