### PR TITLE
Merged upstream tag 1.1.1e

### PR DESCRIPTION
**Pull request by christianpaquin**

### CODE REVIEW

**Comment by dstebila** [comment]
When I run `circleci local execute --job ubuntu-bionic-x86_64` I get a bunch of connection failures (the CI tests above didn't do connection tests):

```
test_openssl.test_connection('ecdsa', 'firesaber', 23652) ... FAILED
test_openssl.test_connection('ecdsa', 'p256_lightsaber', 23680) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'oqs_kem_default', 23691) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_oqs_kem_default', 23692) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'frodo640aes', 23693) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'frodo640shake', 23694) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'frodo976aes', 23695) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'frodo976shake', 23696) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'frodo1344aes', 23697) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'frodo1344shake', 23698) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'bike1l1cpa', 23699) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'bike1l3cpa', 23700) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'bike1l1fo', 23701) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'bike1l3fo', 23702) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'kyber512', 23703) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'kyber768', 23704) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'kyber1024', 23705) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'newhope512cca', 23706) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'newhope1024cca', 23707) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'ntru_hps2048509', 23708) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'ntru_hps2048677', 23709) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'ntru_hps4096821', 23710) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'ntru_hrss701', 23711) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'lightsaber', 23712) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'saber', 23713) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'firesaber', 23714) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'sidhp434', 23715) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'sidhp503', 23716) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'sidhp610', 23717) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'sidhp751', 23718) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'sikep434', 23719) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'sikep503', 23720) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'sikep610', 23721) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'sikep751', 23722) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_frodo640aes', 23723) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_frodo640shake', 23724) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_frodo976aes', 23725) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_frodo976shake', 23726) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_frodo1344aes', 23727) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_frodo1344shake', 23728) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_bike1l1cpa', 23729) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_bike1l3cpa', 23730) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_bike1l1fo', 23731) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_bike1l3fo', 23732) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_kyber512', 23733) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_kyber768', 23734) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_kyber1024', 23735) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_newhope512cca', 23736) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_newhope1024cca', 23737) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_ntru_hps2048509', 23738) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_ntru_hps2048677', 23739) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_ntru_hps4096821', 23740) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_ntru_hrss701', 23741) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_lightsaber', 23742) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_saber', 23743) ... FAILED
test_openssl.test_connection('oqs_sig_default', 'p256_firesaber', 23744) ... FAILED
...
```

**Comment by baentsch** [comment]
Hmm -- correct, connection tests are only done in the nightly runs to not delay a 'mostly working' (apparently not in this case) commit -- maybe we should change this, i.e., have at least one platform do the full connection test suite (?) -- takes more than half an hour by now, however due to the long list of algorithms.... suggestions welcome.

**Comment by christianpaquin** [comment]
I'll take a look about the failing test tonight. Yes, I think we should put at least a full connection test per commit. < 1h seems like an ok price to pay for these infrequent PRs.

**Comment by baentsch** [comment]
Agree. Will you simply remove one of the `-noconn` from the checkin-test job in the `.circleci/config.yml` when doing the next checkin or shall I do a PR?

**Comment by christianpaquin** [comment]
> Agree. Will you simply remove one of the `-noconn` from the checkin-test job in the `.circleci/config.yml` when doing the next checkin or shall I do a PR?

Probably best to do a different PR, just for scoping it to one purpose.

**Comment by christianpaquin** [comment]
The merge was not simple, I had to resolve a lot of conflicts manually. I re-inspected the diff between 1.1.1d and 1.1.1e, and between 1.1.1e and our fork; didn't find anything obvious. I'll need to trace the error. Few runs I tried locally worked, I'll enable connection tests on this PR after all to help guide what to test.

**Comment by christianpaquin** [comment]
`ssl/t1_lib.c`'s `sigalg_security_bits` was introduced in 1.1.1e. It needs to be modified to return the security bits of the OQS algs.

**Comment by baentsch** [comment]
> Probably best to do a different PR, just for scoping it to one purpose.

Done.

**Comment by christianpaquin** [comment]
Sometimes we get the following error:
```
error:14095126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_laye
r_s3.c:303
```

This code block has been added in 1.1.1e, so I need to see what is going on.

**Comment by christianpaquin** [comment]
I think the problem is with our `oqs_test/scripts/do_openssl-111.sh` script. I get the same error when I run the exchange with classical KEX and auth algs: killing the server process seems to trigger the new 111e error ("unexpected eof while reading" I mentioned above). I tried to terminate the connection correctly by passing `Q` to the client (after `GET /`), but that doesn't seem to work. Anyone with better scripting jediness knows how to do that? (@dstebila?)

**Comment by christianpaquin** [comment]
They've [announced 1.1.1f](https://mta.openssl.org/pipermail/openssl-announce/2020-March/000168.html), to be released on March 31st.

**Comment by dstebila** [comment]
When looking at the output, I noticed that sometimes a session ticket was being sent and sometimes not.  That made me think that maybe the problem had to do with something being closed before the session ticket was received.  Disabling session tickets seems to have solved it, at least so far all the tests are passing on my `circleci local execute --job ubuntu-bionic-x86_64`.

There are also some open issues in OpenSSL about changes in EOF behaviour which may be related:
- https://github.com/openssl/openssl/issues/11378
- https://github.com/openssl/openssl/issues/11209

**Comment by christianpaquin** [comment]
Looking at recent commits on the upstream [OpenSSL_1_1_1-stable](https://github.com/openssl/openssl/commits/OpenSSL_1_1_1-stable), it looks like they are reverting some "unexpected EOF" changes. We should probably put this on the ice until they release 1.1.1f tomorrow, and incorporate these changes as well.

**Comment by christianpaquin** [comment]
I'm preparing a new branch integrating the 1.1.1f changes.

**Pull request closed without merging**
